example = {
	'--variable': {
		'lang': 'pl',
		'fontsize': '12pt',
		'papersize': 'a4paper'
	},
	'--from': ['markdown', 'footnotes', 'backtick_code_blocks', 'inline_notes', 'raw_html'],
	'--output': 'document.pdf',
	'--toc': True,
	'--toc-depth' : 3,
}


# example = {
# 	'--metadata': {
# 		'lang': 'pl-PL'
# 	},
# 	'--variable': {
# 		'lang': 'pl',
# 		'fontsize': '12pt',
# 		'papersize': 'a4paper',
# 		'geometry':"inner=3cm, outer=3cm, top=2.5cm, bottom=2.5cm"
# 	},
# 	'--from': ['markdown', 'footnotes', 'backtick_code_blocks', 'inline_notes', 'raw_html'],
# 	'--to': [],
# 	'--output': 'document.pdf',
# 	'--data-dir': '',
# 	'--parse-raw' : False,
# 	'--smart' : False,
# 	'--old-dashes' : False,
# 	'--base-header-level' : 0,
# 	'--indented-code-classes': False,
# 	'--filter': '',
# 	'--normalize' : False,
# 	'--preserve-tabs' : False,
# 	'--tab-stop' : 0,
# 	'--track-changes' : 'accept',
# 	'--extract-media' : '',
# 	'--standalone' : False,
# 	'--template' : '',
# 	'--print-default-template' : '',
# 	'--print-default-data-file' : '',
# 	'--dpi' : 150,
# 	'--no-wrap' : False,
# 	'--wrap' : 'auto',
# 	'--columns' : 10,
# 	'--toc': True,
# 	'--toc-depth' : 3,
# 	'--no-highlight' : False,
# 	'--highlight-style' : 'tango',
# 	'--include-in-header' : '',
# 	'--include-before-body' : '',
# 	'--include-after-body' : '',
# 	'--self-contained' : False,
# 	'--html-q-tags' : False,
# 	'--ascii' : False,
# 	'--reference-links' : False,
# 	'--atx-headers' : False,
# 	'--chapters' : True,
# 	'--number-sections' : False,
# 	'--number-offset' : 0,
# 	'--no-tex-ligatures' : False,
# 	'--listings' : True,
# 	'--incremental' : False,
# 	'--slide-level' : 0,
# 	'--section-divs' : False,
# 	'--default-image-extension' : 'png',
# 	'--email-obfuscation' : 'none',
# 	'--id-prefix' : '',
# 	'--title-prefix' : '',
# 	'--css' : False,
# 	'--reference-odt' : False,
# 	'--reference-docx' : False,
# 	'--epub-stylesheet' : False,
# 	'--epub-cover-image' : False,
# 	'--epub-metadata' : False,
# 	'--epub-embed-font': False,
# 	'--epub-chapter-level': False,
# 	'--latex-engine': False,
# 	'--latex-engine-opt': False,
# 	'--bibliography' : False,
# 	'--csl' : False,
# 	'--citation-abbreviations' : False,
# }
