# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 380)
        MainWindow.setMinimumSize(QtCore.QSize(400, 380))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("GPANDOC")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vertical_layout_1 = QtWidgets.QVBoxLayout()
        self.vertical_layout_1.setObjectName("vertical_layout_1")
        self.horizontal_layout_1 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_1.setObjectName("horizontal_layout_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontal_layout_1.addWidget(self.label_1)
        self.push_button_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.push_button_1.setFont(font)
        self.push_button_1.setObjectName("push_button_1")
        self.horizontal_layout_1.addWidget(self.push_button_1)
        self.vertical_layout_1.addLayout(self.horizontal_layout_1)
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.horizontal_layout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacerItem)
        self.check_box_1 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.check_box_1.setFont(font)
        self.check_box_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_box_1.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.check_box_1.setTristate(False)
        self.check_box_1.setObjectName("check_box_1")
        self.horizontal_layout_2.addWidget(self.check_box_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacerItem1)
        self.vertical_layout_1.addLayout(self.horizontal_layout_2)
        self.list_widget_1 = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget_1.setFrameShape(QtWidgets.QFrame.Box)
        self.list_widget_1.setObjectName("list_widget_1")
        self.vertical_layout_1.addWidget(self.list_widget_1)
        self.horizontal_layout_3 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_3.setObjectName("horizontal_layout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontal_layout_3.addWidget(self.label_4)
        self.push_button_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.push_button_2.setFont(font)
        self.push_button_2.setObjectName("push_button_2")
        self.horizontal_layout_3.addWidget(self.push_button_2)
        self.vertical_layout_1.addLayout(self.horizontal_layout_3)
        self.horizonta_layout_4 = QtWidgets.QHBoxLayout()
        self.horizonta_layout_4.setObjectName("horizonta_layout_4")
        self.push_button_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(11)
        self.push_button_3.setFont(font)
        self.push_button_3.setObjectName("push_button_3")
        self.horizonta_layout_4.addWidget(self.push_button_3)
        self.push_button_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_button_4.setFont(font)
        self.push_button_4.setObjectName("push_button_4")
        self.horizonta_layout_4.addWidget(self.push_button_4)
        self.push_button_5 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.push_button_5.setFont(font)
        self.push_button_5.setObjectName("push_button_5")
        self.horizonta_layout_4.addWidget(self.push_button_5)
        self.vertical_layout_1.addLayout(self.horizonta_layout_4)
        self.horizontalLayout.addLayout(self.vertical_layout_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        self.menuUstawienia = QtWidgets.QMenu(self.menubar)
        self.menuUstawienia.setObjectName("menuUstawienia")
        self.menuPomoc = QtWidgets.QMenu(self.menubar)
        self.menuPomoc.setObjectName("menuPomoc")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionO_GPandoc = QtWidgets.QAction(MainWindow)
        self.actionO_GPandoc.setObjectName("actionO_GPandoc")
        self.actionO_Autorach = QtWidgets.QAction(MainWindow)
        self.actionO_Autorach.setObjectName("actionO_Autorach")
        self.actionInstrukcja_uzycia = QtWidgets.QAction(MainWindow)
        self.actionInstrukcja_uzycia.setObjectName("actionInstrukcja_uzycia")
        self.actionInterfejs = QtWidgets.QAction(MainWindow)
        self.actionInterfejs.setObjectName("actionInterfejs")
        self.actionPreferencje = QtWidgets.QAction(MainWindow)
        self.actionPreferencje.setObjectName("actionPreferencje")
        self.menuUstawienia.addAction(self.actionPreferencje)
        self.menuUstawienia.addAction(self.actionInterfejs)
        self.menuPomoc.addAction(self.actionInstrukcja_uzycia)
        self.menuPomoc.addSeparator()
        self.menuPomoc.addAction(self.actionO_GPandoc)
        self.menuPomoc.addAction(self.actionO_Autorach)
        self.menubar.addAction(self.menuUstawienia.menuAction())
        self.menubar.addAction(self.menuPomoc.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_1.setText(_translate("MainWindow", "1. Wybierz pliki do zaimportowania:"))
        self.push_button_1.setText(_translate("MainWindow", "Wybierz pliki"))
        self.label_2.setText(_translate("MainWindow", "Lista wybranych plików:"))
        self.check_box_1.setText(_translate("MainWindow", "Łącz dokumenty"))
        self.label_4.setText(_translate("MainWindow", "2. Przepis (Wygląd dokumentu):"))
        self.push_button_2.setText(_translate("MainWindow", "Wybierz przepis"))
        self.push_button_3.setText(_translate("MainWindow", "Wygeneruj "))
        self.push_button_4.setText(_translate("MainWindow", "Usuń zaznaczone"))
        self.push_button_5.setText(_translate("MainWindow", "Usuń wszystko"))
        self.menuUstawienia.setTitle(_translate("MainWindow", "Ustawienia"))
        self.menuPomoc.setTitle(_translate("MainWindow", "Pomoc"))
        self.actionO_GPandoc.setText(_translate("MainWindow", "O GPandoc"))
        self.actionO_Autorach.setText(_translate("MainWindow", "O Autorach"))
        self.actionInstrukcja_uzycia.setText(_translate("MainWindow", "Instrukcja użycia"))
        self.actionInterfejs.setText(_translate("MainWindow", "Interfejs"))
        self.actionPreferencje.setText(_translate("MainWindow", "Preferencje"))

