# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow,  QFileDialog, QTextEdit, QPushButton
from PyQt5.QtGui import QIcon

class UI_MainWindow(QMainWindow):
    
    def __init__(self):
        super().__init__()
        self.init_ui()
        
    def init_ui(self):
        main_window = QtWidgets.QWidget()
        main_window.setObjectName("main_window")
        main_window.resize(470, 470)
        main_window.setMinimumSize(QtCore.QSize(400, 380))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setBold(False)
        font.setWeight(50)
        main_window.setFont(font)
        main_window.setWindowTitle("GPANDOC")
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.vertical_layout_3 = QtWidgets.QVBoxLayout(self.central_widget)
        self.vertical_layout_3.setObjectName("vertical_layout_3")
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("vertical_layout")
        self.horizontal_layout_1 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_1.setObjectName("horizontal_layout_1")
        self.label_1 = QtWidgets.QLabel(self.central_widget)

        #font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontal_layout_1.addWidget(self.label_1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_1.addItem(spacerItem)
        self.push_button_1 = QtWidgets.QPushButton(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        self.push_button_1.setFont(font)
        self.push_button_1.setObjectName("push_button_1")
        self.horizontal_layout_1.addWidget(self.push_button_1)
        spacer_item_1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_1.addItem(spacer_item_1)
        self.vertical_layout.addLayout(self.horizontal_layout_1)
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        spacer_item_2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacer_item_2)
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        
        # font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        
        self.label_2.setFont(font)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.horizontal_layout_2.addWidget(self.label_2)
        spacer_item_3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacer_item_3)
        spacer_item_4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacer_item_4)
        self.checkBox_1 = QtWidgets.QCheckBox(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_1.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.checkBox_1.setTristate(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontal_layout_2.addWidget(self.checkBox_1)
        spacer_item_5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacer_item_5)
        spacer_item_6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacer_item_6)
        self.vertical_layout.addLayout(self.horizontal_layout_2)
        self.list_widget = QtWidgets.QListWidget(self.central_widget)
        self.list_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.list_widget.setObjectName("list_widget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.list_widget.addItem(item)

        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_widget.addItem(item)
        self.vertical_layout.addWidget(self.list_widget)
        self.horizontal_layout_3 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_3.setObjectName("horizontal_layout_3")
        self.label_4 = QtWidgets.QLabel(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontal_layout_3.addWidget(self.label_4)
        spacer_item_7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_3.addItem(spacer_item_7)
        self.push_button_2 = QtWidgets.QPushButton(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(10)
        self.push_button_2.setFont(font)
        self.push_button_2.setObjectName("push_button_2")
        self.horizontal_layout_3.addWidget(self.push_button_2)
        self.vertical_layout.addLayout(self.horizontal_layout_3)
        self.horizontal_layout_4 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontal_layout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontal_layout_4.setSpacing(6)
        self.horizontal_layout_4.setObjectName("horizontal_layout_4")
        spacer_item_8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_4.addItem(spacer_item_8)
        self.label_3 = QtWidgets.QLabel(self.central_widget)
        self.label_3.setObjectName("label_3")
        self.horizontal_layout_4.addWidget(self.label_3)
        spacer_item_9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_4.addItem(spacer_item_9)
        spacer_item_10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_4.addItem(spacer_item_10)
        self.combo_box = QtWidgets.QComboBox(self.central_widget)
        self.combo_box.setMinimumSize(QtCore.QSize(200, 0))
        self.combo_box.setSizeIncrement(QtCore.QSize(0, 0))
        self.combo_box.setObjectName("combo_box")
        self.horizontal_layout_4.addWidget(self.combo_box)
        self.vertical_layout.addLayout(self.horizontal_layout_4)
        self.horizontal_layout_5 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_5.setObjectName("horizontal_layout_5")
        spacer_item_11 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_5.addItem(spacer_item_11)
        self.push_button_3 = QtWidgets.QPushButton(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(12)
        self.push_button_3.setFont(font)
        self.push_button_3.setObjectName("push_button_3")
        self.horizontal_layout_5.addWidget(self.push_button_3)
        self.vertical_layout.addLayout(self.horizontal_layout_5)
        self.vertical_layout_3.addLayout(self.vertical_layout)
        self.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 470, 19))
        self.menu_bar.setObjectName("menu_bar")
        self.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        self.show()
        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        main_window.setWindowTitle("GPANDOC")
        _translate = QtCore.QCoreApplication.translate
        self.label_1.setText(_translate("main_window", "1. Wybierz pliki do zaimportowania:"))
        self.push_button_1.setText(_translate("main_window", "Wybierz pliki"))
        self.label_2.setText(_translate("main_window", "Lista wybranych plików:"))
        self.checkBox_1.setText(_translate("main_window", "Łącz dokumenty"))
        __sorting_enabled = self.list_widget.isSortingEnabled()
        self.list_widget.setSortingEnabled(False)

        self.list_widget.setSortingEnabled(__sorting_enabled)
        self.label_4.setText(_translate("main_window", "2. Przepis (format, czcionka, marginesy itp):"))
        self.push_button_2.setText(_translate("main_window", "Wybierz przepis"))
        self.label_3.setText(_translate("main_window", "Lista gotowych przepisów:"))
        self.push_button_3.setText(_translate("main_window", "Zapisz"))
        self.show()
